### ISSUE TITLE
Periodically check for Angular updates

### ISSUE THREAD

**Issue by duluca** [duluca/angular-evergreen#2]
After installing the package via VS Code:

- on project launch detect if package.json exists
- if @angular/cli exists
- start periodically checking for updates

MVP - focus on ng update'able packages

**Comment by kentonbmax** [comment]
Please clarify the last bullet 'start periodically' assume while vsc is running?

**Comment by duluca** [comment]
yes, while vsc is running

**Comment by kentonbmax** [comment]
Will start every time the extension is loaded against a workspace. I fail to see valid use case otherwise.

**Comment by kentonbmax** [comment]
@duluca please clarify 'focus on ng update'able packages' is this a cli check or is there a list we must maintain?

**Comment by kentonbmax** [comment]
Will be handled after child process worked out.
