### ISSUE TITLE
Figure out dealing with child processes

### ISSUE THREAD

**Issue by duluca** [duluca/angular-evergreen#24]
https://nodejs.org/api/child_process.html

https://github.com/weinand/vscode-processes

**Comment by kentonbmax** [comment]
I would suggest this one. [execa](https://www.npmjs.com/package/execa)

**Comment by kentonbmax** [comment]
So thinking we need to update @angular/cli first? Then how should we handle 

Your global Angular CLI version (7.0.6) is greater than your local
version (6.0.8). The local Angular CLI version is used.
