### ISSUE TITLE
Store upgrade settings per project 

### ISSUE THREAD

**Issue by duluca** [duluca/angular-evergreen#6]
package.json setting: 

		"ng-evergreen": {
			"channel": stable (default) or next
                  }
                 with #5 implemented
		"ng-evergreen": {
			"channel": stable (default), rc, beta, alpha
                  }

**Comment by kentonbmax** [comment]
@duluca should be its own evergreen.json stored in .vscode? Reason is because the packag.json does not install extensions and should contain only the bits needed for the app. Extensions are optional by developer unless that para-dime has changed recently?

**Comment by duluca** [comment]
@kentonbmax yes, you're right, we should store it in `.vscode/settings.json`
